config/routes.rb
SecondQuarterlyProject::Application.routes.draw do
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :users, :except => [:destroy, :index]

  resources :welcome, :only => [:index] do
    collection do
      get '/splash' => 'welcome#splash'
    end
  end

  resources :jobs do
    collection do
      get '/x' => 'jobs#x'
      get '/query' => 'jobs#query'
      post '/query' => 'jobs#import'
      post :order_list
      get '/scrape'
      post '/scrape' => 'jobs#cscrape'
    end
    member do
      get :select
      post :complete
    end
  end

  root :to => 'welcome#splash'
end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id          :integer          not null, primary key
#  url         :text
#  name        :string(255)
#  description :text
#  company     :string(255)
#  industry    :string(255)
#  location    :string(255)
#  job_type    :string(255)
#  deadline    :date
#  website     :string(255)
#  tags        :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  tank_id     :integer
#  lat         :float
#  lon         :float
#  completed   :boolean          default(FALSE)
#

class Job < ActiveRecord::Base
  attr_accessible :company, :deadline, :description, :industry, :job_type, :location, :name, :tags, :url, :website, :tank_id, :lat, :lon
  validates :name, :url, :presence => true
  belongs_to :tank

  before_save :geocode

  def add_from_idealist(input)
    doc = Nokogiri::HTML(open(input))
    # NAME
    self[:name] = doc.xpath("//div[@id='contentHeader']/h1").text
    # COMPANY
    self[:company] = doc.xpath("//p[@id='listing-sub-title']/a").text
    # JOB LISTING URL
    self[:url] = input
    # # DESCRIPTION
    self[:description] = doc.xpath("//div[@id='listing-description']").text.gsub("\t","") + doc.xpath("//div[@id='listing-instructions']").text.gsub("\t","")
    # # JOB TYPE
    # self[:job_type] = doc.xpath("//section[@id='leader']/h4").text
    # # LOCATION (NOT GEO-LOCATED)
    self[:location] = doc.xpath("//div[@id='box-Location']/div[@class='body']/div[@class='contentGroup']/div[@class='content']/dl/dd").text
    # # WEBSITE URL
    # idealist_page = "http://www.idealist.org" + doc.xpath("//div[@id='contentHeader']/p[@id='listing-sub-title']/a").first.attributes['href'].text
    # new_doc = Nokogiri::HTML(open(idealist_page))
    # index = new_doc.xpath("//div[@class='contentGroup']/div[@class='content']/dl/dt").text.split(':').find_index("Website")
    # self[:website] = doc.xpath("//div[@class = 'title ']/a").first.attributes['href'].text
    self.save
    # # NEED TO MAKE CASES IN CASE SOMETHING BREAKS
  end

  def add_from_authentic_jobs(input)
    doc = Nokogiri::HTML(open(input))
    # NAME
    self[:name] = doc.xpath("//div[@class='role']/h1").text
    # COMPANY
    self[:company] = doc.xpath("//hgroup/h2").first.text.gsub(/[\t\n]/,"")
    # JOB LISTING URL
    self[:url] = input
    # DESCRIPTION
    self[:description] = doc.xpath("//div[@class='role']/section[@id = 'description']").text.gsub("\t","")
    # JOB TYPE
    self[:job_type] = doc.xpath("//section[@id='leader']/h4").text
    # LOCATION (NOT GEO-LOCATED)
    self[:location] = doc.xpath("//a[@id='location']/span").text
    # WEBSITE URL
    self[:website] = doc.xpath("//div[@class = 'title ']/a").first.attributes['href'].text
    self.save
    # NEED TO MAKE CASES IN CASE SOMETHING BREAKS
  end

  def add_from_indeed(input)
    doc = Nokogiri::HTML(open(input))
    # NAME
    self[:name] = doc.xpath("//b[@class='jobtitle']").text
    # COMPANY
    self[:company] = doc.xpath("//span[@class='company']").text
    # JOB LISTING URL
    self[:url] = input
    # DESCRIPTION
    self[:description] = doc.xpath("//span[@class='summary']").text
    # JOB TYPE
    # self[:job_type] = doc.xpath("//section[@id='leader']/h4").text
    # LOCATION (NOT GEO-LOCATED)
    self[:location] = doc.xpath("//span[@class='location']").text
    # # WEBSITE URL
    # self[:website] = doc.xpath("//div[@class = 'title ']/a").first.attributes['href'].text
    self.save
    # NEED TO MAKE CASES IN CASE SOMETHING BREAKS
  end

  def add_from_37signals(input)
    doc = Nokogiri::HTML(open(input))
    # NAME
    self[:name] = doc.xpath("//div[@class='listing-header-container']/h1").text
    # COMPANY
    self[:company] = doc.xpath("//span[@class='company']").text
    # JOB LISTING URL
    self[:url] = input
    # DESCRIPTION
    self[:description] = doc.xpath("//div[@class='listing-container']").text
    # JOB TYPE
    # self[:job_type] = doc.xpath("//section[@id='leader']/h4").text
    # LOCATION (NOT GEO-LOCATED)
    self[:location] = doc.xpath("//span[@class='location']").text.split(': ')[1]
    # # WEBSITE URL
    # self[:website] = doc.xpath("//div[@class = 'title ']/a").first.attributes['href'].text
    self.save
    # NEED TO MAKE CASES IN CASE SOMETHING BREAKS
  end

  def geocode
    result = Geocoder.search(self.location).first
    if result.present?
      self.lat = result.latitude
      self.lon = result.longitude
    end
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :is_logged_in

  def index
    @jobs = list if @auth.has_jobs?
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def edit
    @job = Job.find(params[:id])
  end

  def create
    @job = Job.new(params[:job])

    respond_to do |format|
      if @job.save
        @auth.tanks.first.jobs << @job
        @jobs = list
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.js {}
      else
        format.html { render action: "new" }
        format.js {}
      end
    end
  end

  def update
    @job = Job.find(params[:id])
    respond_to do |format|
      if @job.update_attributes(params[:job])
        @jobs = list
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.js
      else
        format.html { render action: "edit" }
        format.js { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    @jobs = list
    @job = @jobs.first
    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.js { }
    end
  end

  def query
  end

  def import

    if params[:authentic].present?
      new_job = Job.new
      new_job.add_from_authentic_jobs(params[:authentic])
      @auth.tanks.first.jobs << new_job
    end

    if params[:idealist].present?
      new_job = Job.new
      new_job.add_from_idealist(params[:idealist])
      @auth.tanks.first.jobs << new_job
    end

    if params[:indeed].present?
      new_job = Job.new
      new_job.add_from_indeed(params[:indeed])
      @auth.tanks.first.jobs << new_job
    end

    if params[:signals].present?
      new_job = Job.new
      new_job.add_from_37signals(params[:signals])
      @auth.tanks.first.jobs << new_job
    end

    @jobs = list
  end

  def select
    @job = Job.find( params[:id] )
    render :json => @job
  end

  def order_list
    @auth.complete_list = !@auth.complete_list
    @auth.save
    @jobs = list
  end

  def complete
    @job = Job.find( params[:id] )
    @job.completed = !@job.completed
    @job.save
    @jobs = list
    @job = @jobs.first
  end

  def x
    # binding.pry
    if params[:url].include?("authenticjobs.com/jobs/")
      new_job = Job.new
      new_job.add_from_authentic_jobs(params[:url])
      @auth.tanks.first.jobs << new_job
    end
    if params[:url].include?("idealist.org")
      new_job = Job.new
      new_job.add_from_idealist(params[:url])
      @auth.tanks.first.jobs << new_job
    end
    if params[:url].include?("indeed.com")
      new_job = Job.new
      new_job.add_from_indeed(params[:url])
      @auth.tanks.first.jobs << new_job
    end
    if params[:url].include?("jobs.37signals.com/jobs")
      new_job = Job.new
      new_job.add_from_37signals(params[:url])
      @auth.tanks.first.jobs << new_job
    end
    redirect_to( params[:url] )
  end

  def scrape
  end

  def cscrape
    doc = Nokogiri::HTML(open( "http://www.authenticjobs.com/" ))

    n = 0

    while n < 5 do
      new_job = Job.new
      new_job.add_from_authentic_jobs('http://www.authenticjobs.com' + doc.xpath("//div[@id='listings-wrapper']/ul[@id='listings']/li/a")[n]['href'])
      @auth.tanks.first.jobs << new_job
      n += 1
    end

    @jobs = list
  end

end

app/views/jobs/_form.html.haml
%h5 Add a New Job & Keep Track
%fieldset
  = form_for @job, :remote => true do |f|
    - if @job.errors.any?
      %div{ :id => "error_explanation" }
        %h4
          we found
          = pluralize(@job.errors.count, "error")
        %ul
          - @job.errors.full_messages.each do |msg|
            %li= msg
    .row
      .large-4.columns
        = f.label :name, "Title"
        = f.text_field :name
      .large-4.columns
        = f.label :company
        = f.text_field :company
      .large-4.columns
        = f.label :website
        = f.text_field :website
    .row
      .large-4.columns
        = f.label :job_type
        = f.text_field :job_type
      .large-4.columns
        = f.label :deadline
        = f.text_field :deadline
      .large-4.columns
        = f.label :location
        = f.text_field :location
    .row
      .large-12.columns
        = f.label :url
        = f.text_field :url
    .row
      .large-12.columns
        = f.label :description
        = f.text_area :description
        = f.submit "Add Job", :class => 'button secondary', :style => 'margin-bottom: 0px'

app/views/jobs/_index.html.haml
- if @jobs.present?
  - @jobs.each do |job|
    %a{ :href => job_path(job), 'data-remote' => true }
      .job
        %h6= "#{job.company} - #{job.name}"
        .hide= job.id

app/views/jobs/_info.html.haml
.row
  .large-12.job_heading
    %h2 Welcome to Akio.
    %p{ :style => 'line-height: 2; padding: 25px 0;' } Akio is a nice little app that helps you easily store job information in one central, non-stressful location. Get started using the icons to the left or drag this <a href="javascript:(function(){location.href='http://evening-stream-8132.herokuapp.com/jobs/x?url='+encodeURIComponent(location.href)})();">add job</a> link to your toolbar.
    %p Akio currently works with 37signals, Indeed.com, Idealist.org, and AuthenticJobs.

app/views/jobs/_show.html.haml
- if @job.present?
  .row.main_nav
    .large-4.columns
      %h6= link_to('Edit', edit_job_path(@job), :remote => true, 'data-reveal-id' => 'modal')
    .large-4.columns
      %h6
        %a{ :href => complete_job_path(@job), 'data-remote' => true, 'data-method' => 'post' }
          - if @job.completed
            uncheck
          - else
            %i{ :class => 'foundicon-checkmark' }
    .large-4.columns
      %h6= link_to( 'Delete', job_path(@job), :method => 'delete', :remote => true )
  .row
    .large-6.columns.table
      .job_heading
        %h1= @job.company
        %h2= @job.name
    .large-6.columns.map_container
      #map_canvas{ :style => ( "display: none;" if @job.location.blank? ) }
      .location
        %em= "#{@job.location} - "
        = link_to("Return to Posting", @job.url, :target => '_blank')
  .row
    .large-12.columns
      %p{ :style => 'line-height: 2; padding: 25px 0;' }= truncate(@job.description, :length => 455, :separator => ' ')
  .main_details
    .row
      .large-3.columns
        %h6= @job.job_type.blank? ? link_to('Add Job Type', edit_job_path(@job), :remote => true, 'data-reveal-id' => 'modal') : @job.job_type
      .large-6.columns
        %h6= @job.website.blank? ? link_to('Add Company Website', edit_job_path(@job), :remote => true, 'data-reveal-id' => 'modal') : link_to("#{@job.website.gsub('http://','')}", "#{@job.website}", :target => '_blank')
      .large-3.columns
        %h6= @job.deadline.blank? ? link_to('Add Deadline', edit_job_path(@job), :remote => true, 'data-reveal-id' => 'modal') : @job.deadline
  %script
    - if @job.location.present?
      = "display_map( #{@job.lat}, #{@job.lon}, 12 );"
      = "add_marker(#{@job.lat}, #{@job.lon}, '#{@job.company}')"
- else
  = render :partial => 'jobs/info'

app/views/jobs/complete.js.erb
// $('#modal').foundation('reveal', 'close');
$('.job_list').empty();
$('.job_list').append('<%=j render :partial => 'jobs/index' %>');
$('.main_view').empty();
$('.main_view').prepend( '<%=j render :partial => 'jobs/show' %>' );

app/views/jobs/create.js.erb
$('#modal').foundation('reveal', 'close');
$('.job_list').empty();
$('.job_list').append('<%=j render :partial => 'jobs/index' %>');

app/views/jobs/cscrape.js.erb
// $('#modal').foundation('reveal', 'close');
$('.job_list').empty();
$('.job_list').append('<%=j render :partial => 'jobs/index' %>');

app/views/jobs/destroy.js.erb
// $('#modal').foundation('reveal', 'close');
$('.job_list').empty();
$('.job_list').append('<%=j render :partial => 'jobs/index' %>');
$('.main_view').empty();
$('.main_view').prepend( '<%=j render :partial => 'jobs/show' %>' );

app/views/jobs/import.js.erb
$('#modal').foundation('reveal', 'close');
$('.job_list').empty();
$('.job_list').append('<%=j render :partial => 'jobs/index' %>');

app/views/jobs/new.js.erb
$('#modal').find('h5').remove();
$('#modal').find('fieldset').remove();
$('#modal').prepend( '<%=j render :partial => 'jobs/form' %>' );

app/views/jobs/order_list.js.erb
$('.job_list').empty();
$('.job_list').append('<%=j render :partial => 'jobs/index' %>');
$('.main_view').empty();
$('.main_view').prepend( '<%=j render :partial => 'jobs/show' %>' );

if($('.job_nav').find('i').first().hasClass('foundicon-folder')) {
  $('.main_view').attr('id','greyed');
  $('.job_nav').find('i').first().removeClass().addClass('foundicon-inbox');
  $('.job_nav').find('li').last().fadeOut(250);
  $('.job_nav').find('li').last().prev().fadeOut(250);
} else {
  $('.main_view').attr('id','');
  $('.job_nav').find('i').first().removeClass().addClass('foundicon-folder');
  $('.job_nav').find('li').last().fadeIn(250);
  $('.job_nav').find('li').last().prev().fadeIn(250);
}

app/views/jobs/query.js.erb
$('#modal').find('h5').remove();
$('#modal').find('fieldset').remove();
$('#modal').prepend( '<%=j render :partial => 'jobs/import_jobs' %>' );

app/views/jobs/scrape.js.erb
$('#modal').find('h5').remove();
$('#modal').find('fieldset').remove();
$('#modal').prepend( '<%=j render :partial => 'jobs/form' %>' );

app/views/jobs/update.js.erb
$('#modal').foundation('reveal', 'close');
$('.job_list').empty();
$('.job_list').append('<%=j render :partial => 'jobs/index' %>');
$('.main_view').empty();
$('.main_view').prepend( '<%=j render :partial => 'jobs/show' %>' );