config/routes.rb
SecondQuarterlyProject::Application.routes.draw do
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :users, :except => [:destroy, :index]

  resources :welcome, :only => [:index] do
    collection do
      get '/splash' => 'welcome#splash'
    end
  end

  resources :jobs do
    collection do
      get '/x' => 'jobs#x'
      get '/query' => 'jobs#query'
      post '/query' => 'jobs#import'
      post :order_list
      get '/scrape'
      post '/scrape' => 'jobs#cscrape'
    end
    member do
      get :select
      post :complete
    end
  end

  root :to => 'welcome#splash'
end

app/views/layouts/_footer.html.erb
<footer>
    <div class="row">
      <div class="large-6 columns">
        <p>&copy; akio</p>
      </div>
      <div class="large-6 columns">
        <ul class="inline-list right">
          <li><a href="#">About</a></li>
          <li><a href="#">Contact</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1 class=""><%= link_to("akio", welcome_index_path) %></h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Left Nav Section -->
    <ul class="left">
      <!--<li class="divider"></li>
      <li><%#= link_to("Graphs", '#') %>
      <li class="divider"></li> -->
    </ul>

    <!-- Right Nav Section -->
    <ul class="right">
      <li class="divider"></li>
      <% if @auth.present? %>
      <!-- <li><%#= link_to("Give Me Something New", scrape_jobs_path, :method => 'post', :remote => true ) %></li> -->
      <li class="divider"></li>
      <li><%= link_to("My Account", @auth) %></li>
      <li class="divider"></li>
      <li><%= link_to("Logout", login_path, :method => 'delete') %></li>
      <li class="divider"></li>
      <% else %>
      <li><%= link_to("Create Account", new_user_path) %></li>
      <li class="divider"></li>
      <li><%= link_to("Login", login_path) %></li>
      <li class="divider"></li>
      <% end %>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 8]>         <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width" />
  <title>// akio</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE']}&sensor=false" %>
  <%= csrf_meta_tags %>

  <script src="http://bryanwreid.com/akio/js/zepto.js"></script>
  <script src="http://bryanwreid.com/akio/js/custom.modernizr.js"></script>
  <script src="http://bryanwreid.com/akio/js/foundation.min.js"></script>
  <script src="http://bryanwreid.com/akio/js/foundation.reveal.js"></script>
  <!-- <script src="http://bryanwreid.com/akio/js/jquery.joyride-2.0.3.js"></script> -->
  <script src="http://bryanwreid.com/akio/js/akio.js"></script>
</head>
<body>
<%= render :partial => 'layouts/nav' %>

<%= yield %>

<%= render :partial => 'layouts/footer' %>

  <!-- body content here! -->

  <script>
  $(document).foundation();
  </script>

</body>
</html>

app/views/layouts/splash.html.erb
<!DOCTYPE html>
<!--[if IE 8]>         <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width" />
  <title>_____</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE']}&sensor=false" %>
  <%= csrf_meta_tags %>
</head>
<body style="background: #25a5e7; display: table; text-align: center; width: 100%;">
  <h1 class="splash"><%= link_to("akio", login_path ) %></h1>

  <!-- body content here -->

  <script>
  $(document).foundation();
  </script>
  <script src='assets/ripple.js'></script>
</body>
</html>